default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>

test:
  <<: *default
  database: rails_boot_test
  username: postgres
  password: Abc123
  host: 192.168.0.72

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>